apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
      name: frontend
    spec:
      containers:
        - image: laurafitz/frontend:latest
          name: frontend
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - containerPort: 3000
            hostPort: 31926
            name: client
            protocol: TCP

