apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  selector:
    component: frontend
  clusterIP: None
  ports:
  - name: client
    port: 80
    targetPort: 3000
    nodePort: 31926
    protocol: TCP
  type: LoadBalancer
